//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Common.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.Common.Logic.Properties.ConfigStrings", typeof(ConfigStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ArgumentException.
        /// </summary>
        public static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ArgumentNullException.
        /// </summary>
        public static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ArgumentOutOfRangeException.
        /// </summary>
        public static string ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ca-ES.
        /// </summary>
        public static string Catalan {
            get {
                return ResourceManager.GetString("Catalan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DbConnection.
        /// </summary>
        public static string DbConnection {
            get {
                return ResourceManager.GetString("DbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server = localhost; Database = VuelingDB; Integrated Security = True;.
        /// </summary>
        public static string DbConnectionString {
            get {
                return ResourceManager.GetString("DbConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DirectoryNotFoundException.
        /// </summary>
        public static string DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-GB.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FileNotFoundException.
        /// </summary>
        public static string FileNotFoundException {
            get {
                return ResourceManager.GetString("FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tipoFichero.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FormatException.
        /// </summary>
        public static string FormatException {
            get {
                return ResourceManager.GetString("FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IOException.
        /// </summary>
        public static string IOException {
            get {
                return ResourceManager.GetString("IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListadoAlumnos.json.
        /// </summary>
        public static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OutOfMemoryException.
        /// </summary>
        public static string OutOfMemoryException {
            get {
                return ResourceManager.GetString("OutOfMemoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OverflowException.
        /// </summary>
        public static string OverflowException {
            get {
                return ResourceManager.GetString("OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PlatformNotSupportedException.
        /// </summary>
        public static string PlatformNotSupportedException {
            get {
                return ResourceManager.GetString("PlatformNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es-ES.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE DATABASE VuelingDB ON PRIMARY  
        ///                (NAME = VuelingDB_Data,  
        ///                FILENAME = &apos;C:\\Users\\andreu.conesa\\Documents\\  VuelingDBData.mdf&apos; ,  
        ///                SIZE = 2MB, MAXSIZE = 10MB, FILEGROWTH = 10%)  
        ///                LOG ON (NAME = VuelingDB_Log,  
        ///                FILENAME = &apos;C:\\Users\\andreu.conesa\\Documents\\ VuelingDBLog.ldf&apos;  ,  
        ///                SIZE = 1MB,  
        ///                MAXSIZE = 5MB,  
        ///                FILEGROWTH = 10%).
        /// </summary>
        public static string spCreateDatabaseQuery {
            get {
                return ResourceManager.GetString("spCreateDatabaseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE Students 
        ///                        (ID INTEGER IDENTITY(1,1) PRIMARY KEY, 
        ///                        GUID NVARCHAR(50), 
        ///                        Nombre NVARCHAR(50),  
        ///                        Apellidos NVARCHAR(50),  
        ///                        DNI NVARCHAR(50),  
        ///                        FechaNacimiento DateTime2,  
        ///                        Edad INTEGER, 
        ///                        FechaCompletaAlta DateTime2).
        /// </summary>
        public static string spCreateStudentsTableQuery {
            get {
                return ResourceManager.GetString("spCreateStudentsTableQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spDeleteStudent.
        /// </summary>
        public static string spDeleteStudent {
            get {
                return ResourceManager.GetString("spDeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE dbo.spDeleteStudent @GUID nvarchar(50) AS   
        ///                        BEGIN  
        ///                        DELETE FROM [dbo].[Students]  
        ///                    WHERE GUID = @GUID  
        ///                    END.
        /// </summary>
        public static string spDeleteStudentQuery {
            get {
                return ResourceManager.GetString("spDeleteStudentQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spInsertStudent.
        /// </summary>
        public static string spInsertStudent {
            get {
                return ResourceManager.GetString("spInsertStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE dbo.spInsertStudent  
        ///                        @GUID nvarchar(50), 
        ///                        @Nombre nvarchar(50), 
        ///                        @Apellidos nvarchar(50), @DNI nvarchar(50) , 
        ///                        @FechaNacimiento datetime2(7), @Edad int , 
        ///                        @FechaCompletaAlta datetime2(7) 
        ///                        AS  
        ///                        BEGIN SET NOCOUNT ON;                         
        ///                        INSERT INTO [dbo].[Students] (GUID, Nombre, Apellidos, [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string spInsertStudentQuery {
            get {
                return ResourceManager.GetString("spInsertStudentQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spSelectAllStudents.
        /// </summary>
        public static string spSelectAllStudents {
            get {
                return ResourceManager.GetString("spSelectAllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE dbo.spSelectAllStudents  
        ///                        
        ///                        AS  
        ///                        BEGIN  
        ///                        Select * from [dbo].[Students]                          
        ///                        END.
        /// </summary>
        public static string spSelectAllStudentsQuery {
            get {
                return ResourceManager.GetString("spSelectAllStudentsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spSelectByGuid.
        /// </summary>
        public static string spSelectByGuid {
            get {
                return ResourceManager.GetString("spSelectByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE dbo.spSelectByGuid @GUID nvarchar(50) AS  
        ///                        BEGIN  
        ///                        Select * FROM [dbo].[Students]  
        ///                    WHERE GUID = @GUID  
        ///                    END.
        /// </summary>
        public static string spSelectByGuidQuery {
            get {
                return ResourceManager.GetString("spSelectByGuidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spUpdateByGuid.
        /// </summary>
        public static string spUpdateByGuid {
            get {
                return ResourceManager.GetString("spUpdateByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE PROCEDURE dbo.spUpdateByGuid @GUID nvarchar(50), 
        ///                        @Nombre nvarchar(50), @Apellidos nvarchar(50), 
        ///                        @DNI nvarchar(50), @FechaNacimiento datetime2(7)  
        ///                         AS  
        ///                        BEGIN  
        ///                        UPDATE [dbo].[Students]  
        ///                        SET Nombre = @Nombre,  
        ///                        Apellidos = @Apellidos,  
        ///                        DNI = @DNI,  
        ///                        FechaNacimiento = @FechaNac [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string spUpdateByGuidQuery {
            get {
                return ResourceManager.GetString("spUpdateByGuidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TargetException.
        /// </summary>
        public static string TargetException {
            get {
                return ResourceManager.GetString("TargetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListadoAlumnos.txt.
        /// </summary>
        public static string TxtFile {
            get {
                return ResourceManager.GetString("TxtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ListadoAlumnos.xml.
        /// </summary>
        public static string XmlFile {
            get {
                return ResourceManager.GetString("XmlFile", resourceCulture);
            }
        }
    }
}
